#!/bin/bash

./script/build nrf52840 UART_trans \
    -DOT_LOG_LEVEL=DEBG \
    -DOT_LOG_OUTPUT=PLATFORM_DEFINED \
    -DOT_LOG_MAX_SIZE=1024 \
    -DRTT_BUFFER_SIZE=2048 \
    -DOT_ECDSA=ON \
    -DOT_SRP_CLIENT=ON \
    -DOT_SRP_SERVER=ON \
    -DOT_SRP_SERVER_FAST_START_MDOE=ON \
    -DOT_SERVICE=ON \
    -DOT_NETDATA_PUBLISHER=ON \
    -DOT_WAKEUP_COORDINATOR=ON \
    -DOT_WAKEUP_END_DEVICE=ON \
    -DOT_PEER_TO_PEER=ON \
    -DOT_COEX=ON \
    -DOT_ECSL_TRANSMITTER=ON \
    -DOT_ECSL_RECEIVER=ON

